//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Entity.Tests
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_E_Product
    {
        public T_E_Product()
        {
            this.T_E_Picture = new HashSet<T_E_Picture>();
        }
    
        public long ProductId { get; set; }
        public string Description { get; set; }
        public int Ranking { get; set; }
    
        public virtual ICollection<T_E_Picture> T_E_Picture { get; set; }
    }
}
